server:
  port: 8092
spring:
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 192.168.103.67
    port: 5672
    username: tianjl@123.net
    password: tianjingle
    virtual-host: /